name: ifcy
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: 2.1.3  #latest version
  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  get_ip: ^0.3.0
  redux_remote_devtools: ^0.0.7
  redux_logging: ^0.3.0
  json_annotation: ^3.0.0
  sqflite: ^1.1.6+3
  shared_preferences: ^0.5.3+4
  flutter_spinkit: "^3.1.0"
  fluro: "^1.5.1"
  badges: ^1.1.0
  charts_flutter: ^0.6.0
  font_awesome_flutter: 8.5.0
  flutter_downloader: ^1.1.9
  permission_handler: ^3.2.1+1
  path_provider: 1.2.0
  install_plugin: ^2.0.1
  barcode_scan: ^3.0.1
  image_picker: ^0.6.1
  provider: ^3.0.0+1
  moor_flutter: ^1.7.0
  cached_network_image: ^1.1.1
  flutter_cache_manager: ^1.1.1
  flutter_secure_storage: ^3.2.1+1
  fluttertoast: ^3.1.0
  flutter_easyrefresh: ^2.0.3
  meta: ^1.1.6
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: ^0.3.0
  rxdart: ^0.22.1+1
  jpush_flutter: 0.1.0
  expandable: ^3.0.0+1
  flutter_map_marker_cluster: ^0.2.3
  flutter_map: ^0.7.2


dev_dependencies:
  build_runner: ^1.5.0
  json_serializable: 3.2.0
  moor_generator: ^1.7.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/build_floor.png
    - images/fire.png
    - images/wind.png
    - images/voice2.png
    - images/1.gif
    - images/complete.png
    - images/uncomplete.png
    - images/POINT_TYPE_SMOKE_SENSOR_FAULT.png
    - images/POINT_TYPE_SMOKE_SENSOR_FIRE.png
    - images/POINT_TYPE_SMOKE_SENSOR_NORMAL.png
    - images/POINT_TYPE_TEMPERATURE_SENSOR_FAULT.png
    - images/POINT_TYPE_TEMPERATURE_SENSOR_FIRE.png
    - images/POINT_TYPE_TEMPERATURE_SENSOR_NORMAL.png
    - images/SOUNDER_FAULT.png
    - images/SOUNDER_FIRE.png
    - images/SOUNDER_NORMAL.png
    - images/NULL_COMPLETE.png
    - images/NULL_FAULT.png
    - images/NULL_FIRE.png
    - images/NULL_NORMAL.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
